### ISSUE TITLE
error when install

### ISSUE THREAD

**Issue by mathpopo** [uploadcare/pillow-simd#115]
running build_ext

The headers or library files could not be found for jpeg,
a required dependency when compiling Pillow from source.

Please see the install instructions at:
   https://pillow.readthedocs.io/en/latest/installation.html

Traceback (most recent call last):
  File "setup.py", line 989, in <module>
    setup(
  File "/home/chenxin/disk1/anaconda3/envs/zcls/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/chenxin/disk1/anaconda3/envs/zcls/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/chenxin/disk1/anaconda3/envs/zcls/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/chenxin/disk1/anaconda3/envs/zcls/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/chenxin/disk1/anaconda3/envs/zcls/lib/python3.8/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/chenxin/disk1/anaconda3/envs/zcls/lib/python3.8/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/chenxin/disk1/anaconda3/envs/zcls/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/chenxin/disk1/anaconda3/envs/zcls/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/chenxin/disk1/anaconda3/envs/zcls/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/chenxin/disk1/anaconda3/envs/zcls/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/chenxin/disk1/anaconda3/envs/zcls/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/chenxin/disk1/anaconda3/envs/zcls/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/chenxin/disk1/anaconda3/envs/zcls/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/chenxin/disk1/anaconda3/envs/zcls/lib/python3.8/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/chenxin/disk1/anaconda3/envs/zcls/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/chenxin/disk1/anaconda3/envs/zcls/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/chenxin/disk1/anaconda3/envs/zcls/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/chenxin/.local/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/chenxin/disk1/anaconda3/envs/zcls/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "setup.py", line 804, in build_extensions
    raise RequiredDependencyException(f)
__main__.RequiredDependencyException: jpeg

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 1009, in <module>
    raise RequiredDependencyException(msg)
__main__.RequiredDependencyException: 

The headers or library files could not be found for jpeg,
a required dependency when compiling Pillow from source.

Please see the install instructions at:
   https://pillow.readthedocs.io/en/latest/installation.html

**Comment by homm** [comment]
Please see the install instructions at:
https://pillow.readthedocs.io/en/latest/installation.html
