### ISSUE TITLE
Running setup.py bdist_wheel for pillow-simd ... error

### ISSUE THREAD

**Issue by alexandertsema** [uploadcare/pillow-simd#19]
### What did you do?
pip3 install pillow-simd
### What did you expect to happen?
something promissing
### What actually happened?
trace below
### What versions of Pillow and Python are you using?
python 3.6.3,  Pillow 4.3.0 (classic one) Ubuntu 17.10/16.04 (docker)
Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, Django, or buildout, try to replicate the issue just using Pillow. 

```bash
alex@alex:~$ pip3 install pillow-simd
Collecting pillow-simd
  Using cached Pillow-SIMD-4.3.0.post0.tar.gz
Collecting olefile (from pillow-simd)
Building wheels for collected packages: pillow-simd
  Running setup.py bdist_wheel for pillow-simd ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-zfi50c_8/pillow-simd/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpgmim6gj1pip-wheel- --python-tag cp36:
  Single threaded build, not installing mp_compile:1 processes
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/PIL
  copying PIL/ImageFilter.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/ImageFont.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/GimpGradientFile.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/_tkinter_finder.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/ImageColor.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/ImageStat.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/GdImageFile.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/ImageChops.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/ImagePalette.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/PcfFontFile.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/__init__.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/ImageDraw.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/_util.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/SunImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/ExifTags.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/MicImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/ImageEnhance.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/ImageDraw2.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/ImagePath.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/BdfFontFile.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/JpegPresets.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/ImageShow.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/CurImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/OleFileIO.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/features.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/ImageGrab.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/ImageWin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/TiffTags.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/ContainerIO.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/ImImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/ImageMath.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/version.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/Image.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/_binary.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/MspImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/PngImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/FliImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/FontFile.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/ImageOps.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/ImageMode.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/TarIO.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/PyAccess.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/WalImageFile.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/ImageMorph.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/GifImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/PaletteFile.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/ImageQt.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/ImageSequence.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/PSDraw.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/ImageCms.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/ImageTransform.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/ImageFile.py -> build/lib.linux-x86_64-3.6/PIL
  copying PIL/ImageTk.py -> build/lib.linux-x86_64-3.6/PIL
  running egg_info
  writing Pillow_SIMD.egg-info/PKG-INFO
  writing dependency_links to Pillow_SIMD.egg-info/dependency_links.txt
  writing requirements to Pillow_SIMD.egg-info/requires.txt
  writing top-level names to Pillow_SIMD.egg-info/top_level.txt
  reading manifest file 'Pillow_SIMD.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.sh'
  no previously-included directories found matching 'docs/_static'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching 'codecov.yml'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.landscape.yaml'
  warning: no previously-included files found matching '.travis'
  warning: no previously-included files found matching '.travis/*'
  warning: no previously-included files found matching 'appveyor.yml'
  warning: no previously-included files found matching 'build_children.sh'
  warning: no previously-included files found matching 'tox.ini'
  warning: no previously-included files matching '.git*' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  writing manifest file 'Pillow_SIMD.egg-info/SOURCES.txt'
  copying PIL/.DS_Store -> build/lib.linux-x86_64-3.6/PIL
  running build_ext
  
  
  The headers or library files could not be found for zlib,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  Traceback (most recent call last):
    File "/tmp/pip-build-zfi50c_8/pillow-simd/setup.py", line 788, in <module>
      zip_safe=not (debug_build() or PLATFORM_MINGW), )
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/tmp/pip-build-zfi50c_8/pillow-simd/setup.py", line 577, in build_extensions
      raise RequiredDependencyException(f)
  __main__.RequiredDependencyException: zlib
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-zfi50c_8/pillow-simd/setup.py", line 800, in <module>
      raise RequiredDependencyException(msg)
  __main__.RequiredDependencyException:
  
  The headers or library files could not be found for zlib,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  
  
  ----------------------------------------
  Failed building wheel for pillow-simd
  Running setup.py clean for pillow-simd
Failed to build pillow-simd
Installing collected packages: olefile, pillow-simd
  Running setup.py install for pillow-simd ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-zfi50c_8/pillow-simd/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-0a2hlr7w-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    Single threaded build, not installing mp_compile:1 processes
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageFilter.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageFont.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/GimpGradientFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/_tkinter_finder.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageColor.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageStat.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/GdImageFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageChops.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImagePalette.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/PcfFontFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/__init__.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageDraw.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/_util.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/SunImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ExifTags.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/MicImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageEnhance.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageDraw2.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImagePath.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/BdfFontFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/JpegPresets.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageShow.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/CurImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/OleFileIO.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/features.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageGrab.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageWin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/TiffTags.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ContainerIO.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageMath.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/version.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/Image.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/_binary.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/MspImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/PngImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/FliImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/FontFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageOps.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageMode.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/TarIO.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/PyAccess.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/WalImageFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageMorph.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/GifImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/PaletteFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageQt.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageSequence.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/PSDraw.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageCms.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageTransform.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying PIL/ImageTk.py -> build/lib.linux-x86_64-3.6/PIL
    running egg_info
    writing Pillow_SIMD.egg-info/PKG-INFO
    writing dependency_links to Pillow_SIMD.egg-info/dependency_links.txt
    writing requirements to Pillow_SIMD.egg-info/requires.txt
    writing top-level names to Pillow_SIMD.egg-info/top_level.txt
    reading manifest file 'Pillow_SIMD.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs/_static'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching 'codecov.yml'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching '.travis'
    warning: no previously-included files found matching '.travis/*'
    warning: no previously-included files found matching 'appveyor.yml'
    warning: no previously-included files found matching 'build_children.sh'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'Pillow_SIMD.egg-info/SOURCES.txt'
    copying PIL/.DS_Store -> build/lib.linux-x86_64-3.6/PIL
    running build_ext
    
    
    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    Traceback (most recent call last):
      File "/tmp/pip-build-zfi50c_8/pillow-simd/setup.py", line 788, in <module>
        zip_safe=not (debug_build() or PLATFORM_MINGW), )
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/tmp/pip-build-zfi50c_8/pillow-simd/setup.py", line 577, in build_extensions
        raise RequiredDependencyException(f)
    __main__.RequiredDependencyException: zlib
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zfi50c_8/pillow-simd/setup.py", line 800, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:
    
    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-zfi50c_8/pillow-simd/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-0a2hlr7w-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-zfi50c_8/pillow-simd/

```

**Comment by BigBug92** [comment]
me too

**Comment by Rubiel1** [comment]
We are three now...

**Comment by alexisGandar** [comment]
ANNNND that's four now..

**Comment by hugovk** [comment]
> The headers or library files could not be found for zlib, a required dependency when compiling Pillow from source.
> 
>  Please see the install instructions at:
>     https://pillow.readthedocs.io/en/latest/installation.html
