### ISSUE TITLE
How to install to python docker 

### ISSUE THREAD

**Issue by tonal** [uploadcare/pillow-simd#31]
### What did you do?
I try install pillow-simd to docker
And receiwe failed build:
```
 The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
```
Bat zlib1g-dev install in image and zlib.h has in /usr/include

### What actually happened?
I create Dockerfile:
```
FROM python:3.6.5
RUN apt-get install libtiff5-dev libjpeg62-turbo-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev
RUN pip install -U pip
RUN pip install -U Pillow-SIMD
```
Run build and receive error:
```bash
$ docker build -t pillow-simd .
Sending build context to Docker daemon  70.12MB
Step 1/4 : FROM python:3.6.5
 ---> efb6baa1169f
Step 2/4 : RUN apt-get install libtiff5-dev libjpeg62-turbo-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev
 ---> Using cache
 ---> 44d4338da18e
Step 3/4 : RUN pip install -U pip
 ---> Using cache
 ---> 868a8c2370bb
Step 4/4 : RUN pip install -U Pillow-SIMD
 ---> Running in 92ce2a76a5fa
Collecting Pillow-SIMD
  Downloading Pillow-SIMD-5.1.1.post0.tar.gz (14.2MB)
Building wheels for collected packages: Pillow-SIMD
  Running setup.py bdist_wheel for Pillow-SIMD: started
  Running setup.py bdist_wheel for Pillow-SIMD: finished with status 'error'
  Complete output from command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-68k_4p96/Pillow-SIMD/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-t85ysk4w --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/__init__.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/_binary.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/_tkinter_finder.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/_util.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/BdfFontFile.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/BlpImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ContainerIO.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/CurImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ExifTags.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/features.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/FliImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/FontFile.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/GdImageFile.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/GifImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/GimpGradientFile.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/Image.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageChops.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageCms.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageColor.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageDraw.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageDraw2.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageEnhance.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageFile.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageFilter.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageFont.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageGrab.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageMath.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageMode.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageMorph.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageOps.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImagePalette.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImagePath.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageQt.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageSequence.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageShow.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageStat.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageTk.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageTransform.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImageWin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/JpegPresets.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/MicImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/MspImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/OleFileIO.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/PaletteFile.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/PcfFontFile.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/PdfParser.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/PngImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/PSDraw.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/PyAccess.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/SunImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/TarIO.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/TiffTags.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/version.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/WalImageFile.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
  running egg_info
  writing src/Pillow_SIMD.egg-info/PKG-INFO
  writing dependency_links to src/Pillow_SIMD.egg-info/dependency_links.txt
  writing top-level names to src/Pillow_SIMD.egg-info/top_level.txt
  reading manifest file 'src/Pillow_SIMD.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.c'
  warning: no files found matching '*.h'
  warning: no files found matching '*.sh'
  no previously-included directories found matching 'docs/_static'
  warning: no previously-included files found matching '.appveyor.yml'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching '.codecov.yml'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.landscape.yaml'
  warning: no previously-included files found matching '.travis'
  warning: no previously-included files found matching '.travis/*'
  warning: no previously-included files found matching 'build_children.sh'
  warning: no previously-included files found matching 'tox.ini'
  warning: no previously-included files matching '.git*' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  writing manifest file 'src/Pillow_SIMD.egg-info/SOURCES.txt'
  copying src/PIL/.DS_Store -> build/lib.linux-x86_64-3.6/PIL
  running build_ext
  
  
  The headers or library files could not be found for zlib,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  Traceback (most recent call last):
    File "/tmp/pip-install-68k_4p96/Pillow-SIMD/setup.py", line 795, in <module>
      zip_safe=not (debug_build() or PLATFORM_MINGW), )
    File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/tmp/pip-install-68k_4p96/Pillow-SIMD/setup.py", line 582, in build_extensions
      raise RequiredDependencyException(f)
  __main__.RequiredDependencyException: zlib
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-68k_4p96/Pillow-SIMD/setup.py", line 807, in <module>
      raise RequiredDependencyException(msg)
  __main__.RequiredDependencyException:
  
  The headers or library files could not be found for zlib,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  
  
  ----------------------------------------
  Failed building wheel for Pillow-SIMD
  Running setup.py clean for Pillow-SIMD
Failed to build Pillow-SIMD
Installing collected packages: Pillow-SIMD
  Running setup.py install for Pillow-SIMD: started
    Running setup.py install for Pillow-SIMD: finished with status 'error'
    Complete output from command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-68k_4p96/Pillow-SIMD/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-brhblj2t/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/__init__.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/_binary.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/_tkinter_finder.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/_util.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/BdfFontFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/BlpImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ContainerIO.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/CurImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ExifTags.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/features.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/FliImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/FontFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/GdImageFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/GifImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/GimpGradientFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/Image.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageChops.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageCms.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageColor.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageDraw.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageDraw2.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageEnhance.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageFilter.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageFont.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageGrab.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageMath.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageMode.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageMorph.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageOps.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImagePalette.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImagePath.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageQt.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageSequence.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageShow.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageStat.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageTk.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageTransform.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImageWin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/JpegPresets.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/MicImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/MspImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/OleFileIO.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/PaletteFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/PcfFontFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/PdfParser.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/PngImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/PSDraw.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/PyAccess.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/SunImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/TarIO.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/TiffTags.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/version.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/WalImageFile.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
    running egg_info
    writing src/Pillow_SIMD.egg-info/PKG-INFO
    writing dependency_links to src/Pillow_SIMD.egg-info/dependency_links.txt
    writing top-level names to src/Pillow_SIMD.egg-info/top_level.txt
    reading manifest file 'src/Pillow_SIMD.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs/_static'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.codecov.yml'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching '.travis'
    warning: no previously-included files found matching '.travis/*'
    warning: no previously-included files found matching 'build_children.sh'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'src/Pillow_SIMD.egg-info/SOURCES.txt'
    copying src/PIL/.DS_Store -> build/lib.linux-x86_64-3.6/PIL
    running build_ext
    
    
    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    Traceback (most recent call last):
      File "/tmp/pip-install-68k_4p96/Pillow-SIMD/setup.py", line 795, in <module>
        zip_safe=not (debug_build() or PLATFORM_MINGW), )
      File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/tmp/pip-install-68k_4p96/Pillow-SIMD/setup.py", line 582, in build_extensions
        raise RequiredDependencyException(f)
    __main__.RequiredDependencyException: zlib
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-68k_4p96/Pillow-SIMD/setup.py", line 807, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:
    
    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    
    
    ----------------------------------------
Command "/usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-68k_4p96/Pillow-SIMD/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-brhblj2t/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-68k_4p96/Pillow-SIMD/
The command '/bin/sh -c pip install -U Pillow-SIMD' returned a non-zero code: 1
```

### What versions of Pillow and Python are you using?
Pillow-SIMD 5.1.1
Python 3.6.5

**Comment by homm** [comment]
Sorry, I know nothing about docker. There are docker files used for Pillow testing:
https://github.com/python-pillow/docker-images

Maybe this would help.

**Comment by homm** [comment]
In general, If Pillow can be compiled, Pillow-SIMD would compile too. The difference is Pillow-SIMD doesn't provide precompiled binaries, so it must be compiled each time during installation.

**Comment by tonal** [comment]
If change last line in Dockerfile to
```
RUN pip install -U Pillow
```
All build Ok.

If Add links from `libz.so` and `libjpeg.so` from `/usr/lib/x86_64-linux-gnu/` to` /lib/`
All build Ok.
Your `setup.py` does not find these libraries in a standard location `/usr/lib/x86_64-linux-gnu/`

Work Dockerfile:
```dockerfile
FROM python:3.6
RUN ln -s /usr/lib/x86_64-linux-gnu/libz.so /lib/
RUN ln -s /usr/lib/x86_64-linux-gnu/libjpeg.so /lib/
RUN pip install -U pip
RUN pip install -U Pillow-SIMD
```

**Comment by homm** [comment]
> If change last line in Dockerfile to
```
RUN pip install -U Pillow
```
> All build Ok.

This is because:

> The difference is Pillow-SIMD doesn't provide precompiled binaries, so it must be compiled each time during installation.

If you want to **build** Pillow, you may use

```
$ pip install -U --force-reinstall --no-binary pillow pillow
```

Probably you'll get the same issue.

> Your setup.py does not find these libraries in a standard location /usr/lib/x86_64-linux-gnu/

If you want this to be fixed, you may [fill issue in the upstream repo](https://github.com/python-pillow/Pillow/issues).

**Comment by tonal** [comment]
Thank you
https://github.com/python-pillow/Pillow/issues/3103
