### ISSUE TITLE
A problem with opening an image with webp format in v5.1.1.post0

### ISSUE THREAD

**Issue by lshostenko** [uploadcare/pillow-simd#33]
### What did you do?
I tried to open an image in webp format:
**https://drive.google.com/open?id=10_2biIHzTtepo3Y9C78x6er-8Y2-XXzU**

### What actually happened?
I got an error on MacOS and on travis' server. But it works as expected on my Ubuntu 16.04. Also it is not an issue for v4.3.0.post0.

### What versions of Pillow and Python are you using?
Python 3.6.2, 3.6.3, 3.6.4, Pillow-SIMD==5.1.1.post0

```python
from io import BytesIO
from path import Path

from PIL import Image

image_file = Path('api_assets_test.webp')

with image_file.open(mode='rb') as fp:
    image = Image.open(BytesIO(fp.read()))
```

resultes with OSError

```
fp = <_io.BytesIO object at 0x7f1d8d411f10>, mode = 'r'
    def open(fp, mode="r"):
        """
        Opens and identifies the given image file.
    
        This is a lazy operation; this function identifies the file, but
        the file remains open and the actual image data is not read from
        the file until you try to process the data (or call the
        :py:meth:`~PIL.Image.Image.load` method).  See
        :py:func:`~PIL.Image.new`.
    
        :param fp: A filename (string), pathlib.Path object or a file object.
           The file object must implement :py:meth:`~file.read`,
           :py:meth:`~file.seek`, and :py:meth:`~file.tell` methods,
           and be opened in binary mode.
        :param mode: The mode.  If given, this argument must be "r".
        :returns: An :py:class:`~PIL.Image.Image` object.
        :exception IOError: If the file cannot be found, or the image cannot be
           opened and identified.
        """
    
        if mode != "r":
            raise ValueError("bad mode %r" % mode)
    
        exclusive_fp = False
        filename = ""
        if isPath(fp):
            filename = fp
        elif HAS_PATHLIB and isinstance(fp, Path):
            filename = str(fp.resolve())
    
        if filename:
            fp = builtins.open(filename, "rb")
            exclusive_fp = True
    
        try:
            fp.seek(0)
        except (AttributeError, io.UnsupportedOperation):
            fp = io.BytesIO(fp.read())
            exclusive_fp = True
    
        prefix = fp.read(16)
    
        preinit()
    
        def _open_core(fp, filename, prefix):
            for i in ID:
                try:
                    factory, accept = OPEN[i]
                    if not accept or accept(prefix):
                        fp.seek(0)
                        im = factory(fp, filename)
                        _decompression_bomb_check(im.size)
                        return im
                except (SyntaxError, IndexError, TypeError, struct.error):
                    # Leave disabled by default, spams the logs with image
                    # opening failures that are entirely expected.
                    # logger.debug("", exc_info=True)
                    continue
            return None
    
        im = _open_core(fp, filename, prefix)
    
        if im is None:
            if init():
                im = _open_core(fp, filename, prefix)
    
        if im:
            im._exclusive_fp = exclusive_fp
            return im
    
        if exclusive_fp:
            fp.close()
        raise IOError("cannot identify image file %r"
>                     % (filename if filename else fp))
E       OSError: cannot identify image file <_io.BytesIO object at 0x7f1d8d411f10>
```

**Comment by homm** [comment]
This is not related to Pillow-SIMD. Please, ask it in [original Pillow](https://github.com/python-pillow/Pillow/issues/new).

**Comment by zeiler** [comment]
I have the same issue with pillow-simd==5.3.0post1. This does noot happen in pillow==5.3.0, 2.9.0, 6.0.0, etc. This does seem to be a Pillow-SIMD problem. 
```
(v1) zeiler@q4:~/$ pip install pillow==5.3.0
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting pillow==5.3.0
  Downloading https://files.pythonhosted.org/packages/9a/f6/3b3c82c5c75cae471e02fb584136168d732e17ae9db2d21c5dc82f9790f8/Pillow-5.3.0-cp27-cp27mu-manylinux1_x86_64.whl (2.0MB)
     |████████████████████████████████| 2.0MB 13.3MB/s
Installing collected packages: pillow
Successfully installed pillow-5.3.0
(v1) zeiler@q4:~/$ python utils/tests/test_image.py TestImage.test_image_formats
.
----------------------------------------------------------------------
Ran 1 test in 0.382s

OK
(v1) zeiler@q4:~/$ pip uninstall pillow
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Uninstalling Pillow-5.3.0:
  Would remove:
    /mnt/nfs/zeiler/virtualenv/v1/lib/python2.7/site-packages/PIL/*
    /mnt/nfs/zeiler/virtualenv/v1/lib/python2.7/site-packages/Pillow-5.3.0.dist-info/*
Proceed (y/n)? y
  Successfully uninstalled Pillow-5.3.0
(v1) zeiler@q4:~/$ pip install pillow-simd==5.3.0post1
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting pillow-simd==5.3.0post1
Installing collected packages: pillow-simd
Successfully installed pillow-simd-5.3.0.post1
(v1) zeiler@q4:~/$ python utils/tests/test_image.py TestImage.test_image_formats
/mnt/nfs/zeiler/virtualenv/v1/local/lib/python2.7/site-packages/PIL/Image.py:2655: UserWarning: image file could not be identified because WEBP support not installed
  warnings.warn(message)
> /home/zeiler/utils/image_util.py(43)is_valid_image()
-> print('Bad image: %s' % e)
(Pdb) e
IOError('cannot identify image file <_io.BytesIO object at 0x7f41162a5110>',)
(Pdb) c
Bad image: cannot identify image file <_io.BytesIO object at 0x7f41162a5110>
E
======================================================================
ERROR: test_image_formats (__main__.TestImage)
Test that various formats like jpeg, bmp, png, webp load.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "utils/tests/test_image.py", line 156, in test_image_formats
    load_image(f)
  File "/home/zeiler/utils/image.py", line 230, in load_image
    fd_or_fn = get_image(fd_or_fn)
  File "/home/zeiler/utils/image_util.py", line 29, in get_image
    raise Exception('Invalid image at %s' % imageurl)
Exception: Invalid image at /home/zeiler/tests/data/1.webp

----------------------------------------------------------------------
Ran 1 test in 6.786s
```

**Comment by zeiler** [comment]
pillow-simd-4.3.0.post0 works, anything pillow-simd==5.x.x does not

**Comment by homm** [comment]
Is this still an issue with the latest versions of Pillow-SIMD and libwebp?

**Comment by zeiler** [comment]
I just tried on 6.2.2post1 and it works! Thanks for pinging about this. Probably can close now.
