### ISSUE TITLE
Exception on image thumbnailing

### ISSUE THREAD

**Issue by Globegitter** [uploadcare/pillow-simd#36]
### What did you do?
Run thumbor with pillow-simd==4.3.0.post0 to do on-demand thumbnailing on huge variety of images.

### What did you expect to happen?
The images being thumbnailed

### What actually happened?
When trying to thumbnail `http://1.bp.blogspot.com/-ekhKVXl7xto/T6-2WZMYpTI/AAAAAAAAGiQ/ioOs_2BfXPA/s1600/Images+for+Dog+:++Wallpaper+:+Cute+:+Funny+:+Beautiful+Puppies8.jpg` (the local thumbor url would be: `http://localhost:8888/unsafe/0x390/smart/http://1.bp.blogspot.com/-ekhKVXl7xto/T6-2WZMYpTI/AAAAAAAAGiQ/ioOs_2BfXPA/s1600/Images+for+Dog+:++Wallpaper+:+Cute+:+Funny+:+Beautiful+Puppies8.jpg`) we get the following stacktrace:

```
2018-05-24 11:00:11 thumbor:ERROR [ThreadPool] encoder error -2 when writing image file
Traceback (most recent call last):
  File "/app/thumbor_server/image.binary.runfiles/pypi__thumbor_6_4_2/thumbor/context.py", line 272, in _execute_in_foreground
    returned = operation()
  File "/app/thumbor_server/image.binary.runfiles/pypi__thumbor_6_4_2/thumbor/handlers/__init__.py", line 345, in _load_results
    results = context.request.engine.read(image_extension, quality)
  File "/app/thumbor_server/image.binary.runfiles/pypi__thumbor_6_4_2/thumbor/engines/pil.py", line 262, in read
    self.image.save(img_buffer, FORMATS[ext])
  File "/app/thumbor_server/image.binary.runfiles/pypi__Pillow_SIMD_4_3_0_post0/PIL/Image.py", line 1928, in save
    save_handler(self, fp, filename)
  File "/app/thumbor_server/image.binary.runfiles/pypi__Pillow_SIMD_4_3_0_post0/PIL/JpegImagePlugin.py", line 746, in _save
    ImageFile._save(im, fp, [("jpeg", (0, 0)+im.size, 0, rawmode)], bufsize)
  File "/app/thumbor_server/image.binary.runfiles/pypi__Pillow_SIMD_4_3_0_post0/PIL/ImageFile.py", line 495, in _save
    raise IOError("encoder error %d when writing image file" % s)
IOError: encoder error -2 when writing image file
```

If I change back to normal pillow `4.3.0` it all works fine.

### What versions of Pillow and Python are you using?
Pillow 4.3.0 / 4.3.0.post0
Python 2.7

EDIT:
Also tried with latest pillow simd 5.1.1 and getting basically the same exception:

```
2018-05-24 11:16:02 thumbor:ERROR Could not save as improved image, consider to increase ImageFile.MAXBLOCK
Traceback (most recent call last):
  File "/app/thumbor_server/image.binary.runfiles/pypi__thumbor_6_4_2/thumbor/engines/pil.py", line 266, in read
    self.image.save(img_buffer, self.image.format, **options)
  File "/app/thumbor_server/image.binary.runfiles/pypi__Pillow_SIMD_5_1_1_post0/PIL/Image.py", line 1935, in save
    save_handler(self, fp, filename)
  File "/app/thumbor_server/image.binary.runfiles/pypi__Pillow_SIMD_5_1_1_post0/PIL/JpegImagePlugin.py", line 761, in _save
    ImageFile._save(im, fp, [("jpeg", (0, 0)+im.size, 0, rawmode)], bufsize)
  File "/app/thumbor_server/image.binary.runfiles/pypi__Pillow_SIMD_5_1_1_post0/PIL/ImageFile.py", line 496, in _save
    raise IOError("encoder error %d when writing image file" % s)
IOError: encoder error -2 when writing image file
Bogus input colorspace
2018-05-24 11:16:02 thumbor:ERROR [ThreadPool] encoder error -2 when writing image file
Traceback (most recent call last):
  File "/app/thumbor_server/image.binary.runfiles/pypi__thumbor_6_4_2/thumbor/context.py", line 272, in _execute_in_foreground
    returned = operation()
  File "/app/thumbor_server/image.binary.runfiles/pypi__thumbor_6_4_2/thumbor/handlers/__init__.py", line 345, in _load_results
    results = context.request.engine.read(image_extension, quality)
  File "/app/thumbor_server/image.binary.runfiles/pypi__thumbor_6_4_2/thumbor/engines/pil.py", line 269, in read
    self.image.save(img_buffer, FORMATS[ext])
  File "/app/thumbor_server/image.binary.runfiles/pypi__Pillow_SIMD_5_1_1_post0/PIL/Image.py", line 1935, in save
    save_handler(self, fp, filename)
  File "/app/thumbor_server/image.binary.runfiles/pypi__Pillow_SIMD_5_1_1_post0/PIL/JpegImagePlugin.py", line 761, in _save
    ImageFile._save(im, fp, [("jpeg", (0, 0)+im.size, 0, rawmode)], bufsize)
  File "/app/thumbor_server/image.binary.runfiles/pypi__Pillow_SIMD_5_1_1_post0/PIL/ImageFile.py", line 496, in _save
    raise IOError("encoder error %d when writing image file" % s)
IOError: encoder error -2 when writing image file
2018-05-24 11:16:02 thumbor:ERROR [BaseHander.finish_request] encoder error -2 when writing image file
```

**Comment by homm** [comment]
Please, provide minimal python code which reproduce the error

**Comment by Globegitter** [comment]
@homm I will try and create a minimal example, but just cloning the thumbor repo: https://github.com/thumbor/thumbor and running the integration tests via `nosetests -sv integration_tests/` one can see they pass with pillow but some do not with pillow-simd, same when running the unit tests `coverage run --branch $(which nosetests) -v --with-yanc -s tests/` I get failures just with pillow-simd that I do not get with the matching pillow version.

**Comment by homm** [comment]
Sorry, no success. This is the full list of actions:

```
$ git clone https://github.com/thumbor/thumbor.git
$ cd thumbor
$ python setup.py install
$ cd ../Pillow
$ pip uninstall -y pillow
$ pip uninstall -y pillow-simd
$ CC="ccache cc -mavx2" python ./setup.py develop > /dev/null
$ cd ..
$ nosetests -sv integration_tests/ 
  File "/home/homm/Code/thumbor/thumbor/engines/PIL.py", line 17, in <module>
    from PIL import Image, ImageFile, ImageDraw, ImageSequence, JpegImagePlugin
ImportError: cannot import name Image
```

This is strange because the same import works from ipython.


Even the short variant gives the same result:

```
$ git clone https://github.com/thumbor/thumbor.git
$ cd thumbor
$ python setup.py install
$ nosetests -sv integration_tests/ 
  File "/home/homm/Code/thumbor/thumbor/engines/PIL.py", line 17, in <module>
    from PIL import Image, ImageFile, ImageDraw, ImageSequence, JpegImagePlugin
ImportError: cannot import name Image
```

**Comment by homm** [comment]
OMG, `from __future__ import absolute_import` on top of `thumbor/engines/pil.py` helps. How they didn't face with this already?!

**Comment by Globegitter** [comment]
@homm are you on python 3? Thumbor officially just supports python 2 right now.

**Comment by homm** [comment]
Conversely, this only happens on Python < 3.0. I've created PR: https://github.com/thumbor/thumbor/pull/1074

**Comment by Globegitter** [comment]
Ah so I guess so depending on the OS/setup it can still work. Either way, did you now get to reproduce some of the failures?

**Comment by homm** [comment]
No, I have only one test failed:

```
======================================================================
FAIL: test_single_params (integration_tests.pil_test.PILTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/homm/env/env_ucare/local/lib/python2.7/site-packages/tornado/testing.py", line 136, in __call__
    result = self.orig_method(*args, **kwargs)
  File "/home/homm/Code/thumbor/integration_tests/pil_test.py", line 8, in test_single_params
    self.exec_single_params()
  File "/home/homm/Code/thumbor/integration_tests/__init__.py", line 57, in exec_single_params
    single_dataset(self.retrieve)
  File "/home/homm/Code/thumbor/integration_tests/urls_helpers.py", line 166, in single_dataset
    UrlsTester(fetcher, product(all_options, images))
  File "/home/homm/Code/thumbor/integration_tests/urls_helpers.py", line 126, in __init__
    self.test_group(fetcher, group)
  File "/home/homm/Code/thumbor/integration_tests/urls_helpers.py", line 158, in test_group
    self.report()
  File "/home/homm/Code/thumbor/integration_tests/urls_helpers.py", line 129, in report
    assert len(self.failed_items) == 0, "Failed urls:\n%s" % '\n'.join(self.failed_items)
AssertionError: Failed urls:
unsafe/filters:gifv()/animated.gif
unsafe/filters:gifv(webm)/animated.gif
unsafe/filters:gifv(mp4)/animated.gif
```

This is doesn't look like something related.

> IOError: encoder error -2 when writing image file

From sources: -2 is `s` returned by `encoder.encode()` method, which is `encoder->state.errcode`. In [JpegEncode.c](https://github.com/uploadcare/pillow-simd/blob/simd/5.1.x/src/libImaging/JpegEncode.c#L85) we can found that `state->errcode` is one of consts from [Imaging.h](https://github.com/uploadcare/pillow-simd/blob/simd/5.1.x/src/libImaging/Imaging.h#L526), where -2 is `IMAGING_CODEC_BROKEN`. This const is used in `JpegEncode.c` only once, [at the top most](https://github.com/uploadcare/pillow-simd/blob/simd/5.1.x/src/libImaging/JpegEncode.c#L93). The question is what `setjmp` is and why it isn't success. To be honest, I don't familiar with this part of codecs.

What you can try: 
- Repeat all steps from [Building From Source ](https://pillow.readthedocs.io/en/5.1.x/installation.html#building-from-source)
- Find and delete all not standard libjpeg installation you may have in the system
- Try to build the original Pillow from sources, get the same error (with probability of 99%) and try to ask in [upstream project](https://github.com/python-pillow/Pillow/issues) )

**Comment by Globegitter** [comment]
Thanks for digging into this - interesting, I just noticed if I run thumbor locally with pillow-simd it actually works, the issue is in the docker container - so it seems to me like it could be related to https://github.com/uploadcare/pillow-simd/issues/34

Why does pillow-simd have this extra dependency that pillow does not have?

**Comment by Globegitter** [comment]
Aah, maybe also the image is related to this dependency being built on my native ubuntu machine and then it is runnin in the distroless docker container - anyway, I have more to investigate.

**Comment by Globegitter** [comment]
Yeah changing the docker image fixed the issue for now. Now I ran into a WebP related issue but this can be closed and I will investigate further.
