### ISSUE TITLE
Does this support python 3.7?

### ISSUE THREAD

**Issue by DevinXYang** [uploadcare/pillow-simd#58]
I got an error when I build.
```shell
Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-razmn4fa/pillow-simd/setup.py", line 793, in <module>
      zip_safe=not (debug_build() or PLATFORM_MINGW), )
    File "/home/xddz/anaconda3/envs/pytorch/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/home/xddz/anaconda3/envs/pytorch/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/xddz/anaconda3/envs/pytorch/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/xddz/anaconda3/envs/pytorch/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/xddz/anaconda3/envs/pytorch/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 230, in run
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/home/xddz/anaconda3/envs/pytorch/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 179, in get_tag
      assert tag == supported_tags[0], "%s != %s" % (tag, supported_tags[0])
  AssertionError: ('cp37', 'cp@pyvernodots@m', 'linux_x86_64') != ('cp37', 'cp@PYVERNODOTS@m', 'linux_x86_64')
  ----------------------------------------
  ERROR: Failed building wheel for pillow-simd

```

**Comment by homm** [comment]
Looks like this issue was introduced in minor Python version 3.7.4:

https://askubuntu.com/questions/1164703/installing-openexr-for-python-causes-setuptools-to-fail-with-an-assertion-error

Could you try to update `wheel` and `setuptools` packages to the latest versions.

**Comment by DevinXYang** [comment]
Thx for your help! I've fix this.

**Comment by PolarBean** [comment]
How did you fix!
